# permissions for end users to view sriovt2cards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sriovt2card-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: amd-t2-january
    app.kubernetes.io/part-of: amd-t2-january
    app.kubernetes.io/managed-by: kustomize
  name: sriovt2card-viewer-role
rules:
- apiGroups:
  - sriovfect2.amd.com
  resources:
  - sriovt2cards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovfect2.amd.com
  resources:
  - sriovt2cards/status
  verbs:
  - get
